export type FullMenuItem = {
  id: string;
  name: string;
  price?: string;
  variants?: Array<{
    code: string;
    price: number;
  }>;
  description?: string;
};

export type FullMenuCategory = {
  id: string;
  name: string;
  items: FullMenuItem[];
};

export const fullMenuCategories: FullMenuCategory[] = [
  {
    id: "pizza",
    name: "Pizza",
    items: [
      { id: "pizza-cheese", name: "Cheese Pizza", variants: [{ code: "M", price: 160 }, { code: "L", price: 300 }] },
      { id: "pizza-onion", name: "Onion Pizza", variants: [{ code: "M", price: 170 }, { code: "L", price: 320 }] },
      { id: "pizza-onion-capsicum", name: "Onion Capsicum Pizza", variants: [{ code: "M", price: 180 }, { code: "L", price: 340 }] },
      { id: "pizza-paneer", name: "Paneer Pizza", variants: [{ code: "M", price: 200 }, { code: "L", price: 380 }] },
      { id: "pizza-cheese-corn", name: "Cheese n Corn Pizza", variants: [{ code: "M", price: 180 }, { code: "L", price: 340 }] },
      { id: "pizza-farmhouse", name: "Farmhouse Pizza", variants: [{ code: "M", price: 250 }, { code: "L", price: 450 }] },
      { id: "pizza-veggie-paradise", name: "Veggie Paradise Pizza", variants: [{ code: "M", price: 240 }, { code: "L", price: 420 }] },
      { id: "pizza-peppy-paneer", name: "Peppy Paneer Pizza", variants: [{ code: "M", price: 220 }, { code: "L", price: 400 }] },
      { id: "pizza-mexican-green-wave", name: "Mexican Green Wave Pizza", variants: [{ code: "M", price: 220 }, { code: "L", price: 400 }] },
      { id: "pizza-paneer-makhani", name: "Paneer Makhani Pizza", variants: [{ code: "M", price: 320 }, { code: "L", price: 480 }] },
    ],
  },
  {
    id: "pasta-burger",
    name: "Pasta & Burger",
    items: [
      { id: "pb-aloo-tikki-burger", name: "Aloo Tikki Burger", price: "\u20B980  |  Cheese +\u20B930" },
      { id: "pb-veggies-burger", name: "Veggies Burger", price: "\u20B9100  |  Cheese +\u20B930" },
      { id: "pb-king-burger", name: "King Burger", price: "\u20B9120  |  Cheese +\u20B930" },
      { id: "pb-paneer-maharaja-burger", name: "Paneer Maharaja Burger", price: "\u20B9140  |  Cheese +\u20B930" },
      { id: "pb-red-sauce-pasta", name: "Red Sauce Pasta", price: "\u20B9180" },
      { id: "pb-white-sauce-pasta", name: "White Sauce Pasta", price: "\u20B9200" },
      { id: "pb-french-fries", name: "French Fries", price: "\u20B970" },
      { id: "pb-peri-peri-fries", name: "Peri Peri Fries", price: "\u20B980" },
      { id: "pb-cheese-fries", name: "Cheese Fries", price: "\u20B9100" },
    ],
  },
  {
    id: "soups",
    name: "Soups",
    items: [
      { id: "soups-tomato", name: "Tomato Soup", price: "\u20B980" },
      { id: "soups-lemon-coriander", name: "Lemon coriander Soup", price: "\u20B990" },
      { id: "soups-veg-manchow", name: "Veg Manchow Soup", price: "\u20B980" },
      { id: "soups-veg-hot-sour", name: "Veg hot and sour Soup", price: "\u20B990" },
      { id: "soups-veg-sweet-corn", name: "Veg Sweet corn Soup", price: "\u20B9100" },
      { id: "soups-mushroom", name: "Mushroom Soup", price: "\u20B9100" },
      { id: "soups-cream-mushroom", name: "Cream of Mushroom Soup", price: "\u20B9120" },
    ],
  },
  {
    id: "tandoori-chaap",
    name: "Tandoori Chaap",
    items: [
      { id: "chaap-malai", name: "Malai chaap", variants: [{ code: "H", price: 180 }, { code: "F", price: 250 }] },
      { id: "chaap-afghani", name: "Afghani chaap", variants: [{ code: "H", price: 180 }, { code: "F", price: 250 }] },
      { id: "chaap-hariyali", name: "Hariyali chaap", variants: [{ code: "H", price: 180 }, { code: "F", price: 250 }] },
      { id: "chaap-tandoori", name: "Tandoori chaap", variants: [{ code: "H", price: 150 }, { code: "F", price: 220 }] },
    ],
  },
  {
    id: "tandoori-tikka",
    name: "Tandoori Tikka",
    items: [
      { id: "tikka-malai-paneer", name: "Malai paneer Tikka", variants: [{ code: "H", price: 220 }, { code: "F", price: 320 }] },
      { id: "tikka-afghani-paneer", name: "Afghani Paneer Tikka", variants: [{ code: "H", price: 220 }, { code: "F", price: 320 }] },
      { id: "tikka-hariyali-paneer", name: "Hariyali Paneer Tikka", variants: [{ code: "H", price: 220 }, { code: "F", price: 320 }] },
      { id: "tikka-tandoori-paneer", name: "Tandoori Paneer Tikka", variants: [{ code: "H", price: 200 }, { code: "F", price: 280 }] },
    ],
  },
  {
    id: "south-indian",
    name: "South Indian",
    items: [
      { id: "si-plain-dosa", name: "Plain Dosa", price: "\u20B990" },
      { id: "si-onion-dosa", name: "Onion Dosa", price: "\u20B9100" },
      { id: "si-cheese-dosa", name: "Cheese Dosa", price: "\u20B9120" },
      { id: "si-masala-dosa", name: "Masala Dosa", price: "\u20B9120" },
      { id: "si-butter-masala-dosa", name: "Butter Masala Dosa", price: "\u20B9140" },
      { id: "si-cheese-masala-dosa", name: "Cheese Masala Dosa", price: "\u20B9140" },
      { id: "si-schezwan-plan-dosa", name: "Schezwan Plan Dosa", price: "\u20B9120" },
      { id: "si-schezwan-masala-dosa", name: "Schezwan Masala Dosa", price: "\u20B9140" },
      { id: "si-paneer-dosa", name: "Paneer Dosa", price: "\u20B9160" },
      { id: "si-paneer-butter-dosa", name: "Paneer Butter Dosa", price: "\u20B9180" },
      { id: "si-paneer-schezwan-dosa", name: "Paneer Schezwan Dosa", price: "\u20B9180" },
    ],
  },
  {
    id: "rice-salad",
    name: "Rice & Salad",
    items: [
      { id: "rs-plain-rice", name: "Plain Rice", price: "\u20B9100" },
      { id: "rs-jeera-rice", name: "Jeera Rice", price: "\u20B9110" },
      { id: "rs-mutter-pulao", name: "Mutter Pulao", price: "\u20B9120" },
      { id: "rs-veg-pulao", name: "Veg Pulao", price: "\u20B9130" },
      { id: "rs-veg-biryani", name: "Veg Biryani", price: "\u20B9150" },
      { id: "rs-green-salad", name: "Green salad", price: "\u20B960" },
      { id: "rs-tandoori-salad", name: "Tandoori salad", price: "\u20B960" },
      { id: "rs-tost-salad", name: "Tost salad", price: "\u20B960" },
    ],
  },
  {
    id: "sandwich",
    name: "Sandwich",
    items: [
      { id: "sandwich-veg", name: "Veg Sandwich", price: "\u20B960" },
      { id: "sandwich-veg-grill", name: "Veg Grill Sandwich", price: "\u20B970" },
      { id: "sandwich-cheese", name: "Cheese Sandwich", price: "\u20B980" },
      { id: "sandwich-cheese-grill", name: "Cheese Grill Sandwich", price: "\u20B990" },
      { id: "sandwich-veg-club", name: "Veg Club Sandwich", price: "\u20B9100" },
    ],
  },
  {
    id: "mocktails",
    name: "Mocktails",
    items: [
      { id: "mocktails-lemon-ice-tea", name: "Lemon Ice Tea", price: "\u20B9130" },
      { id: "mocktails-peach-ice-tea", name: "Peach Ice Tea", price: "\u20B9130" },
      { id: "mocktails-mojito", name: "Mojito", price: "\u20B9110" },
      { id: "mocktails-pina-colada", name: "Pina colada", price: "\u20B9110" },
      { id: "mocktails-blue-lagoon", name: "Blue Lagoon", price: "\u20B9110" },
      { id: "mocktails-black-currant", name: "Black currant", price: "\u20B9110" },
      { id: "mocktails-cosmopolitan", name: "Cosmopolitan", price: "\u20B9110" },
      { id: "mocktails-fresh-lime-soda", name: "Fresh Lime soda", price: "\u20B960" },
      { id: "mocktails-roasted-hazelnut", name: "Roasted Hazelnut", price: "\u20B9120" },
    ],
  },
  {
    id: "shakes",
    name: "Shakes",
    items: [
      { id: "shakes-cold-coffee", name: "Cold Coffee", price: "\u20B990  |  Ice Cream +\u20B930" },
      { id: "shakes-vanilla", name: "Vanilla Shake", price: "\u20B9100  |  Ice Cream +\u20B930" },
      { id: "shakes-strawberry", name: "Strawberry Shake", price: "\u20B9100  |  Ice Cream +\u20B930" },
      { id: "shakes-chocolate", name: "Chocolate Shake", price: "\u20B9100  |  Ice Cream +\u20B930" },
      { id: "shakes-oreo", name: "Oreo Shake", price: "\u20B9110  |  Ice Cream +\u20B930" },
      { id: "shakes-kitkat", name: "Kitkat Shake", price: "\u20B9110  |  Ice Cream +\u20B930" },
      { id: "shakes-butterscotch", name: "Butterscotch Shake", price: "\u20B9110  |  Ice Cream +\u20B930" },
    ],
  },
  {
    id: "ice-cream-sweet",
    name: "Ice Cream & Sweet",
    items: [
      { id: "ics-vanilla", name: "Vanilla Ice cream", price: "\u20B990" },
      { id: "ics-strawberry", name: "Strawberry Ice cream", price: "\u20B990" },
      { id: "ics-chocolate", name: "Chocolate Ice cream", price: "\u20B9120" },
      { id: "ics-butter-scotch", name: "Butter Scotch Ice cream", price: "\u20B9100" },
      { id: "ics-tuti-fruti", name: "Tuti Fruti Ice cream", price: "\u20B9120" },
      { id: "ics-mix-bowl", name: "Mix Ice Cream Bowl", price: "\u20B9130" },
      { id: "ics-gulab-jamun", name: "Gulab Jamun", price: "\u20B930" },
      { id: "ics-white-gulab-jamun", name: "White Gulab Jamun", price: "\u20B950" },
      { id: "ics-rasmalai", name: "Rasmalai", price: "\u20B980" },
    ],
  },
  {
    id: "chinese",
    name: "Chinese",
    items: [
      { id: "chinese-bhel", name: "Chinese Bhel", price: "\u20B9110" },
      { id: "chinese-veg-spring-roll", name: "Veg Spring Roll", price: "\u20B9110" },
      { id: "chinese-chilli-potato", name: "Chilli Potato", price: "\u20B9120" },
      { id: "chinese-honey-chilli-potato", name: "Honey Chilli Potato", price: "\u20B9130" },
      { id: "chinese-veg-hakka-noodles", name: "Veg Hakka Noodles", price: "\u20B9130" },
      { id: "chinese-veg-singapore-noodles", name: "Veg Singapore Noodles", price: "\u20B9160" },
      { id: "chinese-veg-manchurian-dry", name: "Veg Manchurian Dry", price: "\u20B9160" },
      { id: "chinese-veg-manchurian-gravy", name: "Veg Manchurian Gravy", price: "\u20B9180" },
      { id: "chinese-veg-fried-rice", name: "Veg Fried Rice", price: "\u20B9150" },
      { id: "chinese-shezwan-fried-rice", name: "Shezwan Fried Rice", price: "\u20B9160" },
      { id: "chinese-veg-singapore-fried-rice", name: "Veg Singapore fried Rice", price: "\u20B9180" },
      { id: "chinese-chilli-paneer-dry", name: "Chilli Paneer Dry", price: "\u20B9180" },
      { id: "chinese-chilli-paneer-gravy", name: "Chilli Paneer Gravy", price: "\u20B9200" },
      { id: "chinese-manchurian-noodles", name: "Manchurian with Noodles", price: "\u20B9280" },
      { id: "chinese-manchurian-fried-rice", name: "Manchurian with Fried Rice", price: "\u20B9280" },
    ],
  },
  {
    id: "special",
    name: "Special",
    items: [
      { id: "special-corn-solden-paper", name: "Corn Solden Paper", price: "\u20B9180" },
      { id: "special-veg-solden-paper", name: "Veg Solden Paper", price: "\u20B9200" },
      { id: "special-veg-crispi", name: "Veg Crispi", price: "\u20B9200" },
      { id: "special-golden-fry-babycorn", name: "Golden Fry Babycorn", price: "\u20B9220" },
      { id: "special-chilli-mushroom", name: "Chilli Mushroom", price: "\u20B9220" },
      { id: "special-kung-pao-mushroom", name: "Kung Pao Mushroom", price: "\u20B9240" },
      { id: "special-paneer-65", name: "Paneer 65", price: "\u20B9240" },
      { id: "special-paneer-satya-sticks", name: "Paneer Satya Sticks", price: "\u20B9280" },
    ],
  },
  {
    id: "bread-roti",
    name: "Bread & Roti",
    items: [
      { id: "br-tandoori-plain-roti", name: "Tandoori Plain Roti", price: "\u20B910" },
      { id: "br-tandoori-butter-roti", name: "Tandoori Butter Roti", price: "\u20B915" },
      { id: "br-tawa-roti", name: "Tawa Roti", price: "\u20B910" },
      { id: "br-butter-tawa-roti", name: "Butter Tawa Roti", price: "\u20B915" },
      { id: "br-rumali-roti", name: "Rumali Roti", price: "\u20B915" },
      { id: "br-missi-roti", name: "Missi Roti", price: "\u20B925" },
      { id: "br-lachha-paratha", name: "Lachha Paratha", price: "\u20B950" },
      { id: "br-plain-naan", name: "Plain Naan", price: "\u20B935" },
      { id: "br-butter-naan", name: "Butter Naan", price: "\u20B940" },
      { id: "br-garlic-naan", name: "Garlic Naan", price: "\u20B945" },
      { id: "br-veg-stuff-naan", name: "Veg Stuff Naan", price: "\u20B960" },
      { id: "br-aloo-paratha", name: "Aloo Paratha", price: "\u20B980" },
      { id: "br-aloo-pyaz-paratha", name: "Aloo Pyaz Paratha", price: "\u20B990" },
      { id: "br-mix-paratha", name: "Mix Paratha", price: "\u20B9120" },
      { id: "br-paneer-paratha", name: "Paneer Paratha", price: "\u20B9120" },
    ],
  },
  {
    id: "papad-raita",
    name: "Papad & Raita",
    items: [
      { id: "pr-dry-papad", name: "Dry Papad", price: "\u20B920" },
      { id: "pr-fry-papad", name: "Fry Papad", price: "\u20B930" },
      { id: "pr-masala-papad", name: "Masala Papad", price: "\u20B945" },
      { id: "pr-plain-raita", name: "Plain Raita", price: "\u20B970" },
      { id: "pr-boondi-raita", name: "Boondi Raita", price: "\u20B9100" },
      { id: "pr-mix-veg-raita", name: "Mix Veg Raita", price: "\u20B9120" },
      { id: "pr-mix-fruit-raita", name: "Mix Fruit Raita", price: "\u20B9140" },
      { id: "pr-pineapple-raita", name: "Pineapple Raita", price: "\u20B9140" },
    ],
  },
  {
    id: "main-course",
    name: "Main Course",
    items: [
      { id: "mc-dal-fry", name: "Dal Fry", price: "\u20B980" },
      { id: "mc-dal-tadka", name: "Dal Tadka", price: "\u20B9100" },
      { id: "mc-dal-makhani", name: "Dal Makhani", price: "\u20B9140" },
      { id: "mc-dal-punjabi", name: "Dal Punjabi", price: "\u20B9180" },
      { id: "mc-aloo-jeera", name: "Aloo Jeera", price: "\u20B9130" },
      { id: "mc-aloo-gobi", name: "Aloo Gobi", price: "\u20B9130" },
      { id: "mc-aloo-gobi-mutter", name: "Aloo Gobi Mutter", price: "\u20B9150" },
      { id: "mc-dam-aloo", name: "Dam Aloo", price: "\u20B9160" },
      { id: "mc-chaap-gravy", name: "Chaap Gravy", price: "\u20B9180" },
      { id: "mc-kadai-chaapp", name: "Kadai Chaapp", price: "\u20B9190" },
      { id: "mc-malai-chaap-gravy", name: "Malai Chaap Gravy", price: "\u20B9200" },
      { id: "mc-chaap-butter-masala", name: "Chaap Butter Masala", price: "\u20B9200" },
      { id: "mc-chaap-handi", name: "Chaap Handi", price: "\u20B9200" },
      { id: "mc-paneer-butter-masala", name: "Paneer Butter Masala", price: "\u20B9220" },
      { id: "mc-paneer-do-pyaza", name: "Paneer do Pyaza", price: "\u20B9220" },
      { id: "mc-kadai-paneer", name: "Kadai Paneer", price: "\u20B9220" },
      { id: "mc-mattar-paneer", name: "Mattar Paneer", price: "\u20B9200" },
      { id: "mc-shahi-paneer", name: "Shahi Paneer", price: "\u20B9220" },
      { id: "mc-paneer-handi", name: "Paneer Handi", price: "\u20B9220" },
      { id: "mc-paneer-lababdar", name: "Paneer Lababdar", price: "\u20B9220" },
      { id: "mc-paneer-korma", name: "Paneer Korma", price: "\u20B9250" },
      { id: "mc-malai-kofta", name: "Malai Kofta", price: "\u20B9250" },
      { id: "mc-palak-paneer", name: "Palak Paneer", price: "\u20B9180" },
      { id: "mc-butter-paneer", name: "Butter Paneer", price: "\u20B9220" },
      { id: "mc-paneer-bhurji", name: "Paneer Bhurji", price: "\u20B9320" },
      { id: "mc-chana-masala", name: "Chana Masala", price: "\u20B9180" },
      { id: "mc-mix-veg", name: "Mix Veg", price: "\u20B9180" },
      { id: "mc-pav-bhaji", name: "Pav Bhaji", price: "\u20B9120" },
    ],
  },
];
